---
version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 10

- package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      day: friday
    open-pull-requests-limit: 10
 
