---
repository:
  description: Ansible Galaxy Collection of System Roles
  topics: ansible, ansible-role, ansible-collection, linux, redhat, centos, fedora, debian, ubuntu
  delete_branch_on_merge: true
  has_wiki: false
